<?php

/**
 * @file
 * Provides an API for generating PDFs.
 */

use Drupal\Core\Routing\RouteMatchInterface;

// Register autoloading of vendor libraries.
$autoload = __DIR__ . '/vendor/autoload.php';
if (file_exists($autoload)) {
  require_once $autoload;
}

/**
 * Implements hook_help().
 */
function pdf_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'pdf_api.settings':
      $output = '';
      $output .= '<p>' . t('Configuration for the dompdf library. For more information, see the <a href=":url" target="_blank">dompdf documentation</a>.', [
        ':url' => 'https://github.com/dompdf/dompdf/blob/master/src/Options.php',
      ]) . '</p>';
      return $output;

    default:
      return '';
  }
}
